image: python

before_script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PWD
    - cd pipeline
    - cd $(dirname $(python -c "from __future__ import print_function;import atuproot;print(atuproot.atuproot_main.__file__)"))
    - patch -p2 < $OLDPWD/atuproot.patch
    - cd -

stages:
  - get_input_data
  - run_fast_curator
  - run_fast_carpenter
  - run_fast_plotter
  - deploy

get_input_data:
  stage: get_input_data
  script:
    - ls -R
    - make input_files
    - ls -R
  artifacts:
    paths:
        - input_files
    expire_in: 2 days

fast_curator_py2:
  image: python:2.7
  stage: run_fast_curator
  script: 
      - ls -R
      - make curator
      - ls -R
  dependencies:
      - get_input_data
  artifacts:
    paths:
        - curator
    expire_in: 2 days

fast_carpenter_py2:
  image: python:2.7
  stage: run_fast_carpenter
  script: 
      - ls -R
      - make carpenter
      - ls -R
  dependencies:
      - fast_curator_py2
  artifacts:
    paths:
        - carpenter
    expire_in: 2 days

fast_plotter_py2:
  image: python:2.7
  stage: run_fast_plotter
  script: make plotter
  dependencies:
      - fast_carpenter_py2
  artifacts:
    paths:
        - plotter
    expire_in: 2 days

    #fast_curator_py3:
    #  image: python:3.7
    #  stage: run_fast_curator
    #  script: make curator
    #  dependencies:
    #      - get_input_data
    #  artifacts:
    #    paths:
    #        - curator
    #    expire_in: 2 days
    #
    #fast_carpenter_py3:
    #  image: python:3.7
    #  stage: run_fast_carpenter
    #  script: make carpenter
    #  dependencies:
    #      - fast_curator_py2
    #  artifacts:
    #    paths:
    #        - carpenter
    #    expire_in: 2 days
    #
    #fast_plotter_py3:
    #  image: python:3.7
    #  stage: run_fast_plotter
    #  script: make plotter
    #  dependencies:
    #      - fast_carpenter_py2
    #  artifacts:
    #    paths:
    #        - plotter
    #    expire_in: 2 days
