image: python

before_script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PWD
    - cd pipeline

stages:
  - get_input_data
  - configure_datasets
  - process_trees
  - make_plots
  - deploy

get_input_data:
  stage: get_input_data
  script:
    - make input_files
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_curator_py2: &FAST_CURATOR
  image: python:2.7
  stage: configure_datasets
  script: 
      - make curator
  dependencies:
      - get_input_data
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_carpenter_py2: &FAST_CARPENTER
  image: python:2.7
  stage: make_plots
  script: 
      - make carpenter
  dependencies:
      - fast_curator_py2
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_plotter_py2: &FAST_PLOTTER
  image: python:2.7
  stage: run_fast_plotter
  script: make plotter
  dependencies:
      - fast_carpenter_py2
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_curator_py3:
  <<: *FAST_CURATOR
  image: python:3.7
  allow_failure: True

fast_carpenter_py3:
  <<: *FAST_CARPENTER
  image: python:3.7
  dependencies:
      - fast_curator_py3
  allow_failure: True

fast_plotter_py3:
  <<: *FAST_PLOTTER
  image: python:3.7
  dependencies:
      - fast_carpenter_py3
