image: python:3.7

before_script:
    - pip install -r requirements.txt
    - '[ -n "$SPECIFIC_PIP_PACKAGES" ] && [[ "$SPECIFIC_PIP_PACKAGES" =~ ^[^\;\&\|]*$ ]] && pip install $SPECIFIC_PIP_PACKAGES'
    - export PYTHONPATH=$PWD
    - cd pipeline

stages:
  - get_input_data
  - configure_datasets
  - process_trees
  - make_plots
  - deploy

get_input_data:
  stage: get_input_data
  script:
    - make input_files
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_curator:
  stage: configure_datasets
  script:
      - make curator
  dependencies:
      - get_input_data
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_carpenter:
  stage: process_trees
  script:
      - make carpenter
  dependencies:
      - fast_curator
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days

fast_plotter:
  stage: make_plots
  script: make plotter
  dependencies:
      - fast_carpenter
  artifacts:
    paths:
        - pipeline
    expire_in: 2 days
