stages:
  - BasicVars: fast_carpenter.define.Define
    #- PtMuon: cms_hep_tutorial.MuonPt
    #- IsoMuons: cms_hep_tutorial.IsoMuons
  - DiMuons: cms_hep_tutorial.DiMuonMass
  - NumberMuons: fast_carpenter.summary.BinnedDataframe
  - EventSelection: fast_carpenter.selection.CutFlow
  - DiMuonMass: fast_carpenter.summary.BinnedDataframe

BasicVars:
  variables:
    - Muon_Pt: "sqrt(Muon_Px ** 2 + Muon_Py ** 2)"
    - IsoMuon_Idx: (Muon_Iso / Muon_Pt) < 0.10
    - NIsoMuon: {reduce: count_true, formula: IsoMuon_Idx}

DiMuons: {mask: IsoMuon_Idx}
#IsoMuons: {iso_var: Muon_Iso, threshold: 0.10}

NumberMuons:
  dataset_col: True
  binning:
    - {in: NMuon, out: nMuons}
  weights: {weighted: EventWeight}

EventSelection:
  weights: {weighted: EventWeight}
  selection:
    All:
      - NIsoMuon >= 2
      - triggerIsoMu24 == 1
        #- subentry == 0 and Muon_Pt > 25

DiMuonMass:
  dataset_col: True
  binning:
      - {in: DiIsoMuon_Mass, out: dimu_mass, bins: {low: 60, high: 120, nbins: 60}}
  weights: {weighted: EventWeight}
